version: '3.4'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:8000:80"
    environment:
      DATABASE_URL: mysql://user:password@database:3306/symfony?serverVersion=8&charset=utf8mb4
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql/mysql-server:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-prootpassword" ] # Command to check health.
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.
      start_period: 10s
    #        container_name: database
    volumes:
      - ./database-setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

volumes:
  db-data:
    name: database
